from app import app, db
from app.models import Spot

def add_sample_data():
    with app.app_context():
        # 既存のテーブルを削除して再作成
        db.drop_all()
        db.create_all()

        # 既存データをクリア
        Spot.query.delete()
        db.session.commit()

        # サンプルデータ - 熊野市のスポットを大幅に追加（約40件）
        spots = [
            # 熊野市駅周辺のスポット
            Spot(
                name="熊野市駅",
                category="駅",
                lat=33.8895,
                lng=136.0997,
                description="熊野市の中心駅。交通の要所",
                photo_url="https://via.placeholder.com/260x160?text=熊野市駅",
                open_time="05:00",
                close_time="23:00",
                recommended_menu="",
                reservation_url=""
            ),
            Spot(
                name="熊野市駅前コンビニ",
                category="コンビニ",
                lat=33.8898,
                lng=136.0995,
                description="駅前の便利なコンビニエンスストア",
                photo_url="https://via.placeholder.com/260x160?text=駅前コンビニ",
                open_time="00:00",
                close_time="23:59",
                recommended_menu="食品、日用品、ATM",
                reservation_url=""
            ),
            Spot(
                name="駅前カフェ",
                category="飲食店",
                lat=33.8892,
                lng=136.0999,
                description="駅前の落ち着いたカフェ",
                photo_url="https://via.placeholder.com/260x160?text=駅前カフェ",
                open_time="07:00",
                close_time="20:00",
                recommended_menu="コーヒー、軽食、サンドイッチ",
                reservation_url=""
            ),
            Spot(
                name="地元居酒屋 くまの",
                category="飲食店",
                lat=33.8888,
                lng=136.1002,
                description="地元の人に愛される居酒屋",
                photo_url="https://via.placeholder.com/260x160?text=地元居酒屋",
                open_time="17:00",
                close_time="23:00",
                recommended_menu="地酒、刺身、焼き物",
                reservation_url=""
            ),
            Spot(
                name="お浜田",
                category="飲食店",
                lat=33.8901,
                lng=136.0993,
                description="新鮮な海鮮料理が自慢の老舗",
                photo_url="https://via.placeholder.com/260x160?text=お浜田",
                open_time="11:00",
                close_time="21:00",
                recommended_menu="刺身、寿司、天ぷら",
                reservation_url="https://example.com/ohamada"
            ),
            Spot(
                name="グリルモリ",
                category="飲食店",
                lat=33.8885,
                lng=136.1005,
                description="本格的なグリル料理専門店",
                photo_url="https://via.placeholder.com/260x160?text=グリルモリ",
                open_time="11:30",
                close_time="22:00",
                recommended_menu="ステーキ、ハンバーグ、洋食",
                reservation_url="https://example.com/grill-mori"
            ),
            Spot(
                name="熊野市駅前駐車場",
                category="駐車場",
                lat=33.8890,
                lng=136.1000,
                description="駅前の大型駐車場",
                photo_url="https://via.placeholder.com/260x160?text=駅前駐車場",
                open_time="00:00",
                close_time="23:59",
                recommended_menu="",
                reservation_url=""
            ),
            Spot(
                name="駅前公衆トイレ",
                category="トイレ",
                lat=33.8893,
                lng=136.0998,
                description="駅前の清潔な公衆トイレ",
                photo_url="https://via.placeholder.com/260x160?text=駅前トイレ",
                open_time="00:00",
                close_time="23:59",
                recommended_menu="",
                reservation_url=""
            ),
            Spot(
                name="熊野ホテル",
                category="ホテル",
                lat=33.8900,
                lng=136.1020,
                description="駅近くの快適なビジネスホテル",
                photo_url="https://via.placeholder.com/260x160?text=熊野ホテル",
                open_time="15:00",
                close_time="11:00",
                recommended_menu="朝食バイキング",
                reservation_url="https://example.com/kumano-hotel"
            ),
            Spot(
                name="ビジネスホテル熊野",
                category="ホテル",
                lat=33.8880,
                lng=136.0985,
                description="駅から徒歩5分のビジネスホテル",
                photo_url="https://via.placeholder.com/260x160?text=ビジネスホテル",
                open_time="16:00",
                close_time="10:00",
                recommended_menu="朝食セット",
                reservation_url="https://example.com/business-hotel"
            ),
            # 世界遺産スポット
            Spot(
                name="熊野本宮大社",
                category="神社",
                lat=33.8467,
                lng=135.7833,
                description="熊野信仰の中心的な神社。世界遺産「紀伊山地の霊場と参詣道」の一部",
                photo_url="https://via.placeholder.com/260x160?text=熊野本宮大社",
                open_time="6:00",
                close_time="18:00",
                recommended_menu="",
                reservation_url="https://example.com/kumano-hongu",
                is_world_heritage=True
            ),
            Spot(
                name="熊野速玉大社",
                category="神社",
                lat=33.8483,
                lng=135.7817,
                description="熊野三山の一つ。世界遺産に登録された歴史ある神社",
                photo_url="https://via.placeholder.com/260x160?text=熊野速玉大社",
                open_time="6:00",
                close_time="18:00",
                recommended_menu="",
                reservation_url="https://example.com/kumano-hayatama",
                is_world_heritage=True
            ),
            Spot(
                name="熊野那智大社",
                category="神社",
                lat=33.6658,
                lng=135.8894,
                description="那智の滝近くにある熊野三山の一つ。世界遺産",
                photo_url="https://via.placeholder.com/260x160?text=熊野那智大社",
                open_time="5:00",
                close_time="17:00",
                recommended_menu="",
                reservation_url="https://example.com/kumano-nachi",
                is_world_heritage=True
            ),
            Spot(
                name="獅子巌",
                category="史跡",
                lat=33.8460,
                lng=135.7820,
                description="熊野本宮大社近くの巨岩。世界遺産",
                photo_url="https://via.placeholder.com/260x160?text=獅子巌",
                open_time="",
                close_time="",
                recommended_menu="",
                reservation_url="",
                is_world_heritage=True
            ),
            Spot(
                name="花の窟神社",
                category="神社",
                lat=33.8475,
                lng=135.7805,
                description="熊野古道沿いにある小さな神社。世界遺産",
                photo_url="https://via.placeholder.com/260x160?text=花の窟神社",
                open_time="",
                close_time="",
                recommended_menu="",
                reservation_url="",
                is_world_heritage=True
            ),
            Spot(
                name="鬼ヶ城",
                category="史跡",
                lat=33.8450,
                lng=135.7850,
                description="熊野古道の難所として知られる場所。世界遺産",
                photo_url="https://via.placeholder.com/260x160?text=鬼ヶ城",
                open_time="",
                close_time="",
                recommended_menu="",
                reservation_url="",
                is_world_heritage=True
            ),
            Spot(
                name="松本峠（熊野古道）",
                category="史跡",
                lat=33.8430,
                lng=135.7880,
                description="熊野古道の重要な峠道。世界遺産",
                photo_url="https://via.placeholder.com/260x160?text=松本峠",
                open_time="",
                close_time="",
                recommended_menu="",
                reservation_url="",
                is_world_heritage=True
            ),
            Spot(
                name="熊野古道（市内区間）",
                category="史跡",
                lat=33.88,
                lng=136.08,
                description="世界遺産「紀伊山地の霊場と参詣道」の参詣道。熊野市内を通過するハイキングコース",
                photo_url="https://via.placeholder.com/260x160?text=熊野古道",
                open_time="",
                close_time="",
                recommended_menu="",
                reservation_url="https://example.com/kumano-kodo",
                is_world_heritage=True
            ),
            Spot(
                name="熊野市世界遺産センター",
                category="史跡",
                lat=33.885,
                lng=136.095,
                description="熊野市の世界遺産について学べる展示施設",
                photo_url="https://via.placeholder.com/260x160?text=世界遺産センター",
                open_time="9:00",
                close_time="17:00",
                recommended_menu="",
                reservation_url="https://example.com/world-heritage-center",
                is_world_heritage=True
            ),
            # 道の駅と観光施設
            Spot(
                name="道の駅 パーク七里御浜",
                category="観光施設",
                lat=33.8920,
                lng=136.0980,
                description="熊野市の特産品が揃う道の駅",
                photo_url="https://via.placeholder.com/260x160?text=道の駅",
                open_time="9:00",
                close_time="18:00",
                recommended_menu="地元産品、お土産",
                reservation_url=""
            ),
            # コンビニ・スーパー
            Spot(
                name="ファミリーマート熊野店",
                category="コンビニ",
                lat=33.8895,
                lng=136.1025,
                description="最新のコンビニエンスストア",
                photo_url="https://via.placeholder.com/260x160?text=ファミマ",
                open_time="00:00",
                close_time="23:59",
                recommended_menu="食品、日用品、ATM",
                reservation_url=""
            ),
            Spot(
                name="セブンイレブン熊野駅前",
                category="コンビニ",
                lat=33.8905,
                lng=136.0990,
                description="駅前のセブンイレブン",
                photo_url="https://via.placeholder.com/260x160?text=セブン",
                open_time="00:00",
                close_time="23:59",
                recommended_menu="食品、飲料、ATM",
                reservation_url=""
            ),
            # レストラン・カフェ
            Spot(
                name="海鮮レストラン 磯丸",
                category="飲食店",
                lat=33.8870,
                lng=136.0990,
                description="新鮮な海鮮料理専門店",
                photo_url="https://via.placeholder.com/260x160?text=磯丸",
                open_time="11:00",
                close_time="22:00",
                recommended_menu="刺身、寿司、海鮮丼",
                reservation_url="https://example.com/isomaru"
            ),
            Spot(
                name="カフェ くまのん",
                category="飲食店",
                lat=33.8885,
                lng=136.1008,
                description="地元の食材を使ったカフェ",
                photo_url="https://via.placeholder.com/260x160?text=カフェくまのん",
                open_time="8:00",
                close_time="18:00",
                recommended_menu="自家製パン、コーヒー、スイーツ",
                reservation_url=""
            ),
            Spot(
                name="ラーメン屋 熊野軒",
                category="飲食店",
                lat=33.8890,
                lng=136.1015,
                description="熊野市名物のラーメン店",
                photo_url="https://via.placeholder.com/260x160?text=熊野軒",
                open_time="11:00",
                close_time="22:00",
                recommended_menu="熊野ラーメン、餃子",
                reservation_url=""
            ),
            # ホテル・宿泊施設
            Spot(
                name="温泉旅館 熊野の湯",
                category="ホテル",
                lat=33.8860,
                lng=136.0970,
                description="熊野の温泉が楽しめる旅館",
                photo_url="https://via.placeholder.com/260x160?text=熊野の湯",
                open_time="15:00",
                close_time="10:00",
                recommended_menu="温泉、会席料理",
                reservation_url="https://example.com/kumano-yu"
            ),
            # 駐車場・トイレ
            Spot(
                name="中央駐車場",
                category="駐車場",
                lat=33.8875,
                lng=136.1000,
                description="市街地の中央にある大型駐車場",
                photo_url="https://via.placeholder.com/260x160?text=中央駐車場",
                open_time="00:00",
                close_time="23:59",
                recommended_menu="",
                reservation_url=""
            ),
            Spot(
                name="熊野城公園トイレ",
                category="トイレ",
                lat=33.8890,
                lng=136.1015,
                description="公園内の清潔な公衆トイレ",
                photo_url="https://via.placeholder.com/260x160?text=公園トイレ",
                open_time="00:00",
                close_time="23:59",
                recommended_menu="",
                reservation_url=""
            ),
            # 土産物店
            Spot(
                name="お土産屋さん 熊野屋",
                category="雑貨屋",
                lat=33.8880,
                lng=136.0995,
                description="熊野名物の土産物が揃う",
                photo_url="https://via.placeholder.com/260x160?text=熊野屋",
                open_time="9:00",
                close_time="21:00",
                recommended_menu="お菓子、工芸品、記念品",
                reservation_url=""
            ),
            # 美浜町のスポット
            Spot(
                name="美浜町コンビニ",
                category="コンビニ",
                lat=33.95,
                lng=136.15,
                description="美浜町の便利なコンビニ",
                photo_url="https://via.placeholder.com/260x160?text=美浜コンビニ",
                open_time="00:00",
                close_time="23:59",
                recommended_menu="食品、日用品",
                reservation_url=""
            ),
            Spot(
                name="美浜温泉ホテル",
                category="ホテル",
                lat=33.92,
                lng=136.12,
                description="美浜町の温泉ホテル",
                photo_url="https://via.placeholder.com/260x160?text=美浜温泉",
                open_time="15:00",
                close_time="11:00",
                recommended_menu="温泉、和食",
                reservation_url="https://example.com/mihama-onsen"
            ),
            Spot(
                name="美浜海鮮レストラン",
                category="飲食店",
                lat=33.94,
                lng=136.14,
                description="美浜町の新鮮な海鮮料理",
                photo_url="https://via.placeholder.com/260x160?text=美浜海鮮",
                open_time="11:00",
                close_time="21:00",
                recommended_menu="刺身、寿司",
                reservation_url="https://example.com/mihama-seafood"
            ),
            # 紀宝町のスポット
            Spot(
                name="紀宝町コンビニ",
                category="コンビニ",
                lat=33.75,
                lng=136.05,
                description="紀宝町のコンビニ",
                photo_url="https://via.placeholder.com/260x160?text=紀宝コンビニ",
                open_time="00:00",
                close_time="23:59",
                recommended_menu="食品、飲料",
                reservation_url=""
            ),
            Spot(
                name="紀宝温泉旅館",
                category="ホテル",
                lat=33.72,
                lng=136.02,
                description="紀宝町の伝統的な温泉旅館",
                photo_url="https://via.placeholder.com/260x160?text=紀宝温泉",
                open_time="15:00",
                close_time="10:00",
                recommended_menu="温泉、郷土料理",
                reservation_url="https://example.com/kiho-onsen"
            ),
            Spot(
                name="紀宝漁港レストラン",
                category="飲食店",
                lat=33.74,
                lng=136.04,
                description="紀宝町の漁港近くのレストラン",
                photo_url="https://via.placeholder.com/260x160?text=紀宝漁港",
                open_time="10:00",
                close_time="20:00",
                recommended_menu="新鮮魚介、郷土料理",
                reservation_url="https://example.com/kiho-fishing"
            ),
            Spot(
                name="紀宝町道の駅",
                category="観光施設",
                lat=33.73,
                lng=136.03,
                description="紀宝町の道の駅。お土産や地元産品が揃う",
                photo_url="https://via.placeholder.com/260x160?text=紀宝道の駅",
                open_time="8:00",
                close_time="18:00",
                recommended_menu="地元産品、お土産",
                reservation_url=""
            )
        ]
        db.session.add_all(spots)
        db.session.commit()
        print("サンプルデータを追加しました")

if __name__ == '__main__':
    add_sample_data()